version: '3.8'
services:
  # MongoDB: https://hub.docker.com/_/mongo/
  mongo:
    image: mongo:4.2
    networks:
      - graylog
    volumes:
      - type: volume
        source: mongo_data
        target: /data/db
    restart: unless-stopped
  # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
    volumes:
      - type: volume
        source: es_data
        target: /usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - graylog
    restart: unless-stopped
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog:
    image: graylog/graylog:4.0
    volumes:
      - type: volume
        source: graylog_data
        target: /usr/share/graylog/data
    secrets:
      - greylog_root_password
    environment:
      # CHANGE ME (must be at least 16 characters)!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: password
      # - GRAYLOG_ROOT_PASSWORD_SHA2=5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8
      # Or use Docker Secrets (See the README.md)
      - GRAYLOG_ROOT_PASSWORD_SHA2=/run/secrets/greylog_root_password
      # Change to the IP address of the machine
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_HTTP_PUBLISH_URI=http://127.0.0.1:9000/
    networks:
      - graylog
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    restart: unless-stopped

# Bridge the graylog network
networks:
  graylog:
    driver: bridge

# Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
# and https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes
volumes:
  mongo_data:
    driver: local
    # external: true
  es_data:
    driver: local
    # external: true
  graylog_data:
    driver: local
    # external: true

# Secrets
secrets:
  greylog_root_password:
    file: ./root_password_hash.txt
    # external: true